server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  redis:
    port: 6379
    host: cache
  application:
    name: GATEWAY-SERVICE

resilience4j:
  CircuitBreaker:
    configs:
      default:
        slidingWindowSize: 5                      #unit request
        permittedNumberOfCallsInHalfOpenState: 2  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 3000             #3 seconds
        registerHealthIndicator: true
    instances:
      authorService:
        baseConfig: default
      postService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true