version: '3'

services:
  #Databases
  author-service-postgre-db:
    image: postgres:13.1-alpine
    restart: always
    container_name: author-service-postgre-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=author-service
      
  post-service-mongo-db:
    image: mongo:latest
    container_name: post-service-mongo-db
    restart: always
    ports:
      - "27017:27017"

  #Internal Services
  gateway-service:
    image: ua.koss/gateway-service:1.0.0
    build:
      context: ./infrastructure/gateway-service/
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - post-service
      - author-service
      - cache
    environment:
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-service:9411/
      - SPRING_ZIPKIN_ENABLED=true
  config-server:
    image: ua.koss/config-server:1.0.0
    build:
      context: ./config-server/
    container_name: config-server
    ports:
      - "8888:8888"
  author-service:
    image: ua.koss/author-service:1.0.0
    build:
      context: ./author-service/
    container_name: author-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - author-service-postgre-db
      - eureka-server
      - zipkin-service
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://author-service-postgre-db:5432/author-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-service:9411/
      - SPRING_ZIPKIN_ENABLED=true
    links:
      - config-server
  post-service:
    image: ua.koss/post-service:1.0.0
    build:
      context: ./post-service/
    container_name: post-service
    ports:
      - "8082:8082"
    depends_on:
      - post-service-mongo-db
      - eureka-server
      - zipkin-service
    links:
      - post-service-mongo-db
    environment:
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-service:9411/
      - SPRING_ZIPKIN_ENABLED=true
  eureka-server:
    image: ua.koss/discovery-service:1.0.0
    build:
      context: ./infrastructure/discovery-service/
    container_name: discovery-service
    ports:
      - "8761:8761"

  #External Services
  zipkin-service:
    image: openzipkin/zipkin:latest
    container_name: zipkin-service
    ports:
      - "9411:9411"
  grafana:
    image: ua.koss/grafana:latest
    container_name: grafana-service
    build:
      context: ./infrastructure/config/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus-service
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infrastructure/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  cache:
    image: redis:6.2-alpine
    container_name: redis-service
    restart: always
    ports:
      - '6379:6379'
networks:
  monitoring: