server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-service

resilience4j:
  CircuitBreaker:
    configs:
      default:
        slidingWindowSize: 5                      #unit request
        permittedNumberOfCallsInHalfOpenState: 2  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 3000             #3 seconds
        registerHealthIndicator: true
    instances:
      authorService:
        baseConfig: default
      postService:
        baseConfig: default