server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  #  zipkin:
  #    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
        - id: authorService
          uri: ${AUTHOR_URL}
          predicates:
            - Path=${AUTHOR_PATH}
#            - Method=GET
          filters:
            - AddRequestHeader=X-Client,web
            - AddResponseHeader=X-Type, something from author service
            - name: CircuitBreaker
              args:
                name: authorService
                fallbackUri: forward:/author-fallback
        - id: postService
          uri: ${POST_URL}
          predicates:
            - Path=${POST_PATH}
            - Method=GET
          filters:
            - AddRequestHeader=X-Client,web
            - AddResponseHeader=X-Type, something from post service
            - name: CircuitBreaker
              args:
                name: postService
                fallbackUri: forward:/post-fallback

resilience4j:
  CircuitBreaker:
    configs:
      default:
        slidingWindowSize: 5                      #unit request
        permittedNumberOfCallsInHalfOpenState: 2  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 3000             #3 seconds
        registerHealthIndicator: true
    instances:
      authorService:
        baseConfig: default
      postService:
        baseConfig: default