apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  ports:
    - port: {{ .Values.authorService.port }}
  selector:
    app: author-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: {{ .Values.authorService.image }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.authorService.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.authorService.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.authorService.datasource.password }}
            - name: SPRING_ZIPKIN_BASE_URL
              value: {{ .Values.authorService.zipkinUrl }}
          ports:
            - containerPort: {{ .Values.authorService.port }}
