apiVersion: v1
kind: Service
metadata:
  name: author-service-postgre-db
spec:
  ports:
    - port: {{ .Values.authorServicePostgreDb.port }}
  selector:
    app: author-service-postgre-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service-postgre-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service-postgre-db
  template:
    metadata:
      labels:
        app: author-service-postgre-db
    spec:
      containers:
        - name: author-service-postgre-db
          image: {{ .Values.authorServicePostgreDb.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.authorServicePostgreDb.password }}
            - name: POSTGRES_USER
              value: {{ .Values.authorServicePostgreDb.username }}
            - name: POSTGRES_DB
              value: {{ .Values.authorServicePostgreDb.database }}
          ports:
            - containerPort: {{ .Values.authorServicePostgreDb.port }}
