apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
    - port: {{ .Values.cache.port }}
  selector:
    app: redis-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis-service
          image: {{ .Values.cache.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: {{ .Values.cache.port }}
