apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
    - port: {{ .Values.configServer.port }}
  selector:
    app: config-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: {{ .Values.configServer.image }}
          resources:
            limits:
              memory: "650Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.configServer.port }}
