apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.discoveryService.port }}
  selector:
    app: discovery-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: {{ .Values.discoveryService.image }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "350m"
          ports:
            - containerPort: {{ .Values.discoveryService.port }}
