apiVersion: v1
kind: Service
metadata:
  name: post-service-mongo-db
spec:
  ports:
    - port: {{ .Values.postServiceMongoDb.port }}
  selector:
    app: post-service-mongo-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service-mongo-db
  template:
    metadata:
      labels:
        app: post-service-mongo-db
    spec:
      containers:
        - name: post-service-mongo-db
          image: {{ .Values.postServiceMongoDb.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: {{ .Values.postServiceMongoDb.port }}
