apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  ports:
    - port: {{ .Values.postService.port }}
  selector:
    app: post-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: {{ .Values.postService.image }}
          resources:
            limits:
              memory: "1024Mi"
              cpu: "256m"
          env:
            - name: SPRING_ZIPKIN_BASE_URL
              value: {{ .Values.postService.zipkinUrl }}
          ports:
            - containerPort: {{ .Values.postService.port }}
