apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  ports:
    - port: {{ .Values.zipkinService.port }}
  selector:
    app: zipkin-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-service
  template:
    metadata:
      labels:
        app: zipkin-service
    spec:
      containers:
        - name: zipkin-service
          image: {{ .Values.zipkinService.image }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "150m"
          ports:
            - containerPort: {{ .Values.zipkinService.port }}
