apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service   
    spec:
      containers:
      - name: author-service
        image: kosstheonly/author-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  selector:
    app: author-service
  ports:
  - port: 8081
    targetPort: 8081
          
